#!/bin/sh
ROOT=/net/electricjungle/ed/ElectricJunglesServlet/scripts
chmod +x /net/electricjungle/ed/ElectricJunglesServlet/scripts/*

for i in `cat $ROOT/machines`;
do
   box=`echo $i | awk -F:  '{ print $1 }'`
   $ROOT/stopjobs $box
done
